[build]
  publish = "_site/"
  command = "npm run netlify:build"

[build.environment]
  JEKYLL_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://giscus.app; frame-src https://giscus.app; style-src 'self' 'unsafe-inline' https://giscus.app; font-src https://giscus.app;"
